# Generated by Django 3.1.1 on 2020-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(max_length=70)),
                ('track', models.CharField(max_length=70)),
                ('book', models.CharField(max_length=70)),
                ('pincode', models.IntegerField()),
                ('village', models.CharField(max_length=70)),
                ('date', models.DateField(null=True)),
                ('payment', models.CharField(choices=[('online', 'online'), ('cod', 'cod')], max_length=70)),
                ('total', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
